### ISSUE TITLE
Installation process

### ISSUE THREAD

**Issue by AirBorne04** [barbatus/angular2-meteor-universal#1]
Hi how can i install this package into my meteor app?

**Comment by mmazloum** [comment]
couldn't find it on Atmosphere, Nor npm, may be to new to be released ?

**Comment by AirBorne04** [comment]
Yes i believe so, but i got it working the version restriction on the meteor-promise version was a bit to restrictive. I put in a pr on this one #3 
Besides this I think it is working nicely!

Thanks for this package, i was looking for something like this since a little while.

**Comment by mmazloum** [comment]
@AirBorne04 did you manage to use it ? if so I'd like to know how you did insert it into your project, I'm trying to use Orionjs CMS on the backend side and use Ionic 2 on the front end And I get lot of rooting problems, I guess this package would help a lot.

**Comment by hlehmann** [comment]
If you follow the examples/app structure with `npm i https://github.com/barbatus/angular2-meteor-universal` it should work isn't it ?

**Comment by AirBorne04** [comment]
i just downloaded the repo copied the folder into my npm modules. Than added linklocal via npm and added `"angular2-meteor-universal": "file:./node_modules/angular2-meteor-universal",` to the package json. Run npm install afterwards, fix dependency mismatches and it worked.
@hlehmann option seems a little easier, I just didn't know it would work like that.

**Comment by mmazloum** [comment]
@hlehmann indeed it worked
@AirBorne04 thanks I was trying the way you described ;-)

I've seen urigo angular meteor was being updated last days as well, are they planning an update of the tutorial ?

However thanks for your help ;-)

**Comment by barbatus** [comment]
It's not ready yet, there is a chance it'll be a part of Angular2-Meteor NPM
